### ISSUE TITLE
Question about one step of your work titled with "Inference for a generalised stochastic block model with unknown number of blocks and non-conjugate edge models"

### ISSUE THREAD

**Issue by masterzhen119** [LU-CSML/lu-csml.github.io#2]
Dear Prof. Ludkin,

My name is Zhen Zhang, one PhD student of The Chinese University of Hong Kong.

Thanks for a great work of weighted SBM community detection. 

When I followed your work, I am confusing with one step, that is random walk for parameters resampling. Since it did not give the details in the paper. So my questions is how to derive the sampling procedure in the following picture?

And what we can gain from that procedure?

Looking for your reply!

Best,

Zhen Zhang
PhD student in Statistics
Research Interests: Data Analysis, Complex Network, Supply Chain
Department of Statistics,
The Chinese University of Hong Kong
Shatin, N.T., Hong Kong

**Comment by LorenzoRimella** [comment]
Hi,

this is the webpage of a reading group, you should contact Prof. Ludkin in a different way.
